`timescale 1ns/1ns

module qpll ();
// generated by  HDL Direct 14.20-p006 14-Mar-2002
// on Tue Jun 10 22:43:17 2003
// from uob_hep_pc007a_lib/QPLL/sch_1

  // global signal glbl.\2v5 ;
  // global signal glbl.gnd;
  // global signal glbl.vcc;
  // global signal glbl.vee;

  wire  unnamed_1_100e111_i60_in;
  wire  unnamed_1_100e111_i60_in_1;
  wire  unnamed_1_100e111_i60_q1;
  wire  unnamed_1_100e111_i60_q1_1;
  wire  unnamed_1_100e111_i60_vbb;
  wire  unnamed_1_100el16_i3_d;
  wire  unnamed_1_100el16_i3_dbar;
  wire  unnamed_1_100el16_i3_q;
  wire  unnamed_1_100el16_i3_qbar;
  wire  unnamed_1_100el16_i3_vbb;
  wire  \unnamed_1_8way-spst_i4_b ;
  wire  \unnamed_1_8way-spst_i4_b_1 ;
  wire  \unnamed_1_8way-spst_i4_b_2 ;
  wire  \unnamed_1_8way-spst_i4_b_3 ;
  wire  \unnamed_1_8way-spst_i4_b_4 ;
  wire  \unnamed_1_8way-spst_i4_b_5 ;
  wire  \unnamed_1_8way-spst_i4_b_6 ;
  wire  unnamed_1_capacitor_i15_a;
  wire  unnamed_1_capacitor_i16_a;
  wire  unnamed_1_capacitor_i24_b;
  wire  unnamed_1_capacitor_i25_a;
  wire  unnamed_1_capacitor_i31_b;
  wire  unnamed_1_capacitor_i49_a;
  wire  unnamed_1_capacitor_i50_b;
  wire  unnamed_1_capacitor_i76_a;
  wire  unnamed_1_capacitor_i77_b;
  wire  \unnamed_1_cc1f-t1a_i5_a1 ;
  wire  \unnamed_1_cc1f-t1a_i5_a2 ;
  wire  unnamed_1_header2x1_i79_b;
  wire  \unnamed_1_led-smd_i35_a1 ;
  wire  \unnamed_1_led-smd_i35_k1 ;
  wire  \unnamed_1_led-smd_i94_k1 ;
  wire  \unnamed_1_led-smd_i95_k1 ;
  wire  \unnamed_1_qpll28-cern_i2_incmos ;
  wire  \unnamed_1_qpll28-cern_i2_lvds160mhz ;
  wire  \unnamed_1_qpll28-cern_i2_lvds160mhz_1 ;
  wire  \unnamed_1_qpll28-cern_i2_lvds80mhz ;
  wire  \unnamed_1_qpll28-cern_i2_lvds80mhz_1 ;
  wire  unnamed_1_resistor_i57_b;
  wire  unnamed_1_resistor_i58_b;
  wire  \unnamed_2_100324-dip_i25_d ;
  wire  \unnamed_2_100324-dip_i25_en ;
  wire  \unnamed_2_100324-dip_i25_op ;
  wire  \unnamed_2_100324-dip_i25_op_1 ;
  wire  \unnamed_2_100324-dip_i26_d ;
  wire  \unnamed_2_100324-dip_i26_op ;
  wire  \unnamed_2_100324-dip_i26_op_1 ;
  wire  \unnamed_2_100324-dip_i27_d ;
  wire  \unnamed_2_100324-dip_i27_op ;
  wire  \unnamed_2_100324-dip_i27_op_1 ;
  wire  \unnamed_2_100324-dip_i28_d ;
  wire  \unnamed_2_100324-dip_i28_op ;
  wire  \unnamed_2_100324-dip_i28_op_1 ;
  wire  \unnamed_2_100324-dip_i29_d ;
  wire  \unnamed_2_100324-dip_i29_op ;
  wire  \unnamed_2_100324-dip_i29_op_1 ;
  wire  \unnamed_2_100324-dip_i30_d ;
  wire  \unnamed_2_100324-dip_i30_op ;
  wire  \unnamed_2_100324-dip_i30_op_1 ;
  wire  unnamed_2_100elt23_i10_d0;
  wire  unnamed_2_100elt23_i10_d0_1;
  wire  unnamed_2_100elt23_i10_d1;
  wire  unnamed_2_100elt23_i10_d1_1;
  wire  unnamed_2_100elt23_i11_d0;
  wire  unnamed_2_100elt23_i11_d0_1;
  wire  unnamed_2_100elt23_i11_d1;
  wire  unnamed_2_100elt23_i11_d1_1;
  wire  unnamed_2_100elt23_i12_d0;
  wire  unnamed_2_100elt23_i12_d0_1;
  wire  unnamed_2_100elt23_i12_d1;
  wire  unnamed_2_100elt23_i12_d1_1;
  wire  \unnamed_2_fuse-smd_i54_a ;
  wire  \unnamed_2_ten-5-dualop_i13_vinn1 ;
  wire  \unnamed_2_ten-5-dualop_i13_vinp1 ;
  wire  unnamed_3_diode_i53_a;
  wire  unnamed_3_diode_i53_k;
  wire  \unnamed_3_fuse-smd_i54_a ;
  wire  unnamed_3_resistor_i100_b;
  wire  unnamed_3_resistor_i101_b;
  wire  unnamed_3_resistor_i102_b;
  wire  unnamed_3_resistor_i103_b;
  wire  unnamed_3_resistor_i104_b;
  wire  unnamed_3_resistor_i105_b;
  wire  unnamed_3_resistor_i106_b;
  wire  unnamed_3_resistor_i107_b;
  wire  unnamed_3_resistor_i108_b;
  wire  unnamed_3_resistor_i109_b;
  wire  unnamed_3_resistor_i110_b;
  wire  unnamed_3_resistor_i111_b;
  wire  unnamed_3_resistor_i112_b;
  wire  unnamed_3_resistor_i113_b;
  wire  unnamed_3_resistor_i114_b;
  wire  unnamed_3_resistor_i76_a;
  wire  unnamed_3_resistor_i77_a;
  wire  unnamed_3_resistor_i78_a;
  wire  unnamed_3_resistor_i81_a;
  wire  unnamed_3_resistor_i81_b;
  wire  unnamed_3_resistor_i82_a;
  wire  unnamed_3_resistor_i82_b;
  wire  unnamed_3_resistor_i83_a;
  wire  unnamed_3_resistor_i83_b;
  wire  unnamed_3_resistor_i84_b;
  wire  unnamed_3_resistor_i85_b;
  wire  unnamed_3_resistor_i86_a;
  wire  unnamed_3_resistor_i96_a;
  wire  unnamed_3_resistor_i97_a;
  wire  unnamed_3_resistor_i98_a;
  wire  unnamed_3_resistor_i99_b;

  wire  \2v5 ;
  wire  page1_2v5;
  wire  gnd;
  wire  page3_gnd;
  wire  page2_gnd;
  wire  page1_gnd;
  wire  vcc;
  wire  page2_vcc;
  wire  page1_vcc;
  wire  vee;
  wire  page3_vee;
  wire  page2_vee;

  assign \2v5  = glbl.\2v5 ;
  assign page1_2v5 = \2v5 ;
  assign gnd = glbl.gnd;
  assign page3_gnd = gnd;
  assign page2_gnd = gnd;
  assign page1_gnd = gnd;
  assign vcc = glbl.vcc;
  assign page2_vcc = vcc;
  assign page1_vcc = vcc;
  assign vee = glbl.vee;
  assign page3_vee = vee;
  assign page2_vee = vee;

  assign gnd  = glbl.gnd;
  assign vcc  = glbl.vcc;
  assign vcc  = glbl.vcc;
  assign \2v5   = glbl.\2v5 ;
  assign gnd  = glbl.gnd;
  assign \2v5   = glbl.\2v5 ;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vcc  = glbl.vcc;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vcc  = glbl.vcc;
  assign \2v5   = glbl.\2v5 ;
  assign gnd  = glbl.gnd;
  assign \2v5   = glbl.\2v5 ;
  assign vcc  = glbl.vcc;
  assign vee  = glbl.vee;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vcc  = glbl.vcc;
  assign vee  = glbl.vee;
  assign gnd  = glbl.gnd;
  assign vee  = glbl.vee;
  assign vcc  = glbl.vcc;
  assign vcc  = glbl.vcc;
  assign vee  = glbl.vee;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vee  = glbl.vee;
  assign vee  = glbl.vee;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  \qpll28-cern  page1_i2  (.autorestart(\unnamed_1_8way-spst_i4_b_4 ),
	.cap(unnamed_1_capacitor_i31_b),
	.error(/* unconnected */),
	.externalcontrol(\unnamed_1_8way-spst_i4_b ),
	.foselect0(\unnamed_1_8way-spst_i4_b_5 ),
	.foselect1(\unnamed_1_8way-spst_i4_b_6 ),
	.foselect2(\unnamed_1_8way-spst_i4_b_3 ),
	.foselect3(\unnamed_1_8way-spst_i4_b_2 ),
	.gnd1(glbl.gnd),
	.gnd2(glbl.gnd),
	.gnd3(glbl.gnd),
	.incmos(\unnamed_1_qpll28-cern_i2_incmos ),
	.inlvds(unnamed_1_capacitor_i25_a),
	.\inlvds* (unnamed_1_capacitor_i24_b),
	.locked(\unnamed_1_led-smd_i35_a1 ),
	.lvds40mhz(unnamed_1_capacitor_i50_b),
	.\lvds40mhz* (unnamed_1_capacitor_i49_a),
	.lvds80mhz(\unnamed_1_qpll28-cern_i2_lvds80mhz_1 ),
	.\lvds80mhz* (\unnamed_1_qpll28-cern_i2_lvds80mhz ),
	.lvds160mhz(\unnamed_1_qpll28-cern_i2_lvds160mhz_1 ),
	.\lvds160mhz* (\unnamed_1_qpll28-cern_i2_lvds160mhz ),
	.mode(\unnamed_1_8way-spst_i4_b_1 ),
	.\reset* (unnamed_1_header2x1_i79_b),
	.thermalpad(glbl.\2v5 ),
	.vdd1(glbl.\2v5 ),
	.vdd2(glbl.\2v5 ),
	.vdd3(glbl.\2v5 ),
	.xtal1(\unnamed_1_cc1f-t1a_i5_a2 ),
	.xtal2(\unnamed_1_cc1f-t1a_i5_a1 ));
  defparam page1_i2.size = 1;

  \100el16  page1_i3  (.d(unnamed_1_100el16_i3_d),
	.\d_bar* (unnamed_1_100el16_i3_dbar),
	.q(unnamed_1_100el16_i3_q),
	.\q_bar* (unnamed_1_100el16_i3_qbar),
	.vbb(unnamed_1_100el16_i3_vbb),
	.vcc(glbl.vcc),
	.vee(glbl.gnd));
  defparam page1_i3.size = 1;

  \8way-spst  page1_i4  (.a({glbl.gnd, glbl.gnd, glbl.gnd, glbl.gnd, glbl.gnd, glbl.gnd, glbl.gnd,
	open_p1$1}),
	.b({\unnamed_1_8way-spst_i4_b_1 , \unnamed_1_8way-spst_i4_b , \unnamed_1_8way-spst_i4_b_5 ,
	\unnamed_1_8way-spst_i4_b_6 , \unnamed_1_8way-spst_i4_b_3 , \unnamed_1_8way-spst_i4_b_2 ,
	\unnamed_1_8way-spst_i4_b_4 , open_p1$2}));
  defparam page1_i4.size = 1;

  \cc1f-t1a  page1_i5  (.a1(\unnamed_1_cc1f-t1a_i5_a1 ),
	.a2(\unnamed_1_cc1f-t1a_i5_a2 ));
  defparam page1_i5.size = 1;

  capacitor page1_i6  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page1_i6.size = 1;

  resistor page1_i9  (.a(unnamed_1_capacitor_i16_a),
	.b(unnamed_1_capacitor_i15_a));
  defparam page1_i9.size = 1;

  resistor page1_i10  (.a(unnamed_1_100el16_i3_vbb),
	.b(unnamed_1_100el16_i3_d));
  defparam page1_i10.size = 1;

  resistor page1_i11  (.a(unnamed_1_100el16_i3_vbb),
	.b(unnamed_1_100el16_i3_dbar));
  defparam page1_i11.size = 1;

  capacitor page1_i15  (.a(unnamed_1_capacitor_i15_a),
	.b(unnamed_1_100el16_i3_d));
  defparam page1_i15.size = 1;

  capacitor page1_i16  (.a(unnamed_1_capacitor_i16_a),
	.b(unnamed_1_100el16_i3_dbar));
  defparam page1_i16.size = 1;

  resistor page1_i17  (.a({glbl.gnd}),
	.b(unnamed_1_100el16_i3_qbar));
  defparam page1_i17.size = 1;

  resistor page1_i18  (.a({glbl.gnd}),
	.b(unnamed_1_100el16_i3_q));
  defparam page1_i18.size = 1;

  resistor page1_i19  (.a({glbl.gnd}),
	.b(unnamed_1_capacitor_i25_a));
  defparam page1_i19.size = 1;

  resistor page1_i20  (.a({glbl.gnd}),
	.b(unnamed_1_capacitor_i24_b));
  defparam page1_i20.size = 1;

  resistor page1_i21  (.a(unnamed_1_capacitor_i25_a),
	.b({glbl.vcc}));
  defparam page1_i21.size = 1;

  resistor page1_i22  (.a(unnamed_1_capacitor_i24_b),
	.b({glbl.vcc}));
  defparam page1_i22.size = 1;

  capacitor page1_i24  (.a(unnamed_1_100el16_i3_q),
	.b(unnamed_1_capacitor_i24_b));
  defparam page1_i24.size = 1;

  capacitor page1_i25  (.a(unnamed_1_capacitor_i25_a),
	.b(unnamed_1_100el16_i3_qbar));
  defparam page1_i25.size = 1;

  resistor page1_i28  (.a({glbl.gnd}),
	.b(\unnamed_1_qpll28-cern_i2_incmos ));
  defparam page1_i28.size = 1;

  capacitor page1_i31  (.a({glbl.gnd}),
	.b(unnamed_1_capacitor_i31_b));
  defparam page1_i31.size = 1;

  \led-smd  page1_i35  (.a1(\unnamed_1_led-smd_i35_a1 ),
	.k1(\unnamed_1_led-smd_i35_k1 ));
  defparam page1_i35.size = 1;

  resistor page1_i37  (.a({glbl.gnd}),
	.b(\unnamed_1_led-smd_i35_k1 ));
  defparam page1_i37.size = 1;

  capacitor page1_i40  (.a({glbl.gnd}),
	.b({glbl.\2v5 }));
  defparam page1_i40.size = 1;

  capacitor page1_i43  (.a({glbl.gnd}),
	.b({glbl.\2v5 }));
  defparam page1_i43.size = 1;

  capacitor page1_i47  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page1_i47.size = 1;

  capacitor page1_i49  (.a(unnamed_1_capacitor_i49_a),
	.b(unnamed_1_100e111_i60_in));
  defparam page1_i49.size = 1;

  capacitor page1_i50  (.a(unnamed_1_100e111_i60_in_1),
	.b(unnamed_1_capacitor_i50_b));
  defparam page1_i50.size = 1;

  resistor page1_i51  (.a(unnamed_1_100e111_i60_in),
	.b(unnamed_1_100e111_i60_vbb));
  defparam page1_i51.size = 1;

  resistor page1_i52  (.a(unnamed_1_100e111_i60_in_1),
	.b(unnamed_1_100e111_i60_vbb));
  defparam page1_i52.size = 1;

  capacitor page1_i53  (.a({glbl.gnd}),
	.b(unnamed_1_100el16_i3_vbb));
  defparam page1_i53.size = 1;

  capacitor page1_i54  (.a({glbl.gnd}),
	.b(unnamed_1_100e111_i60_vbb));
  defparam page1_i54.size = 1;

  resistor page1_i57  (.a({glbl.gnd}),
	.b(unnamed_1_resistor_i57_b));
  defparam page1_i57.size = 1;

  resistor page1_i58  (.a({glbl.gnd}),
	.b(unnamed_1_resistor_i58_b));
  defparam page1_i58.size = 1;

  \100e111  page1_i60  (.in(unnamed_1_100e111_i60_in_1),
	.\in* (unnamed_1_100e111_i60_in),
	.q0(unnamed_1_resistor_i58_b),
	.\q0* (unnamed_1_resistor_i57_b),
	.q1(unnamed_1_100e111_i60_q1),
	.\q1* (unnamed_1_100e111_i60_q1_1),
	.q2(/* unconnected */),
	.\q2* (/* unconnected */),
	.q3(/* unconnected */),
	.\q3* (/* unconnected */),
	.q4(/* unconnected */),
	.\q4* (/* unconnected */),
	.q5(/* unconnected */),
	.\q5* (/* unconnected */),
	.q6(/* unconnected */),
	.\q6* (/* unconnected */),
	.q7(/* unconnected */),
	.\q7* (/* unconnected */),
	.q8(/* unconnected */),
	.\q8* (/* unconnected */),
	.vbb(unnamed_1_100e111_i60_vbb),
	.vcc(glbl.vcc),
	.vcco1(glbl.vcc),
	.vcco2(glbl.vcc),
	.vcco3(glbl.vcc),
	.vee(glbl.gnd));
  defparam page1_i60.size = 1;

  capacitor page1_i61  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page1_i61.size = 1;

  resistor page1_i62  (.a(unnamed_1_capacitor_i50_b),
	.b(unnamed_1_capacitor_i49_a));
  defparam page1_i62.size = 1;

  resistor page1_i63  (.a({glbl.gnd}),
	.b(unnamed_1_100e111_i60_q1));
  defparam page1_i63.size = 1;

  resistor page1_i65  (.a({glbl.gnd}),
	.b(unnamed_1_100e111_i60_q1_1));
  defparam page1_i65.size = 1;

  ld1086 page1_i69  (.gnd(glbl.gnd),
	.vin(glbl.vcc),
	.vout(unnamed_1_capacitor_i76_a));
  defparam page1_i69.size = 1;

  capacitor page1_i75  (.a({glbl.vcc}),
	.b({glbl.gnd}));
  defparam page1_i75.size = 1;

  capacitor page1_i76  (.a(unnamed_1_capacitor_i76_a),
	.b({glbl.gnd}));
  defparam page1_i76.size = 1;

  capacitor page1_i77  (.a({glbl.gnd}),
	.b(unnamed_1_capacitor_i77_b));
  defparam page1_i77.size = 1;

  capacitor page1_i78  (.a({glbl.gnd}),
	.b(unnamed_1_capacitor_i76_a));
  defparam page1_i78.size = 1;

  header2x1 page1_i79  (.a({glbl.gnd}),
	.b(unnamed_1_header2x1_i79_b));
  defparam page1_i79.size = 1;

  \resistor-net-7c  page1_i80  (.a(glbl.\2v5 ),
	.b({\unnamed_1_8way-spst_i4_b_1 , \unnamed_1_8way-spst_i4_b , \unnamed_1_8way-spst_i4_b_5 ,
	\unnamed_1_8way-spst_i4_b_6 , \unnamed_1_8way-spst_i4_b_3 , \unnamed_1_8way-spst_i4_b_2 ,
	\unnamed_1_8way-spst_i4_b_4 }));
  defparam page1_i80.size = 7;

  \sk-lemo-00  page1_i81  (.a(unnamed_1_100e111_i60_q1),
	.b({glbl.gnd , glbl.gnd , glbl.gnd , glbl.gnd}));

  \sk-lemo0b-2f-pcb  page1_i82  (.a(unnamed_1_resistor_i58_b),
	.b(unnamed_1_resistor_i57_b));
  defparam page1_i82.size = 1;

  \sk-lemo0b-2f-pcb  page1_i83  (.a(\unnamed_1_qpll28-cern_i2_lvds160mhz_1 ),
	.b(\unnamed_1_qpll28-cern_i2_lvds160mhz ));
  defparam page1_i83.size = 1;

  \sk-lemo0b-2f-pcb  page1_i84  (.a(\unnamed_1_qpll28-cern_i2_lvds80mhz_1 ),
	.b(\unnamed_1_qpll28-cern_i2_lvds80mhz ));
  defparam page1_i84.size = 1;

  \sk-lemo0b-2f-pcb  page1_i85  (.a(unnamed_1_capacitor_i15_a),
	.b(unnamed_1_capacitor_i16_a));
  defparam page1_i85.size = 1;

  inductor page1_i86  (.a(unnamed_1_capacitor_i76_a),
	.b({glbl.\2v5 }));
  defparam page1_i86.size = 1;

  resistor page1_i87  (.a(unnamed_1_capacitor_i76_a),
	.b({glbl.\2v5 }));
  defparam page1_i87.size = 1;

  capacitor page1_i88  (.a({glbl.gnd}),
	.b({glbl.\2v5 }));
  defparam page1_i88.size = 1;

  capacitor page1_i89  (.a({glbl.gnd}),
	.b({glbl.\2v5 }));
  defparam page1_i89.size = 1;

  inductor page1_i90  (.a(unnamed_1_capacitor_i77_b),
	.b({glbl.vcc}));
  defparam page1_i90.size = 1;

  resistor page1_i91  (.a(unnamed_1_capacitor_i77_b),
	.b({glbl.vcc}));
  defparam page1_i91.size = 1;

  \term-blk-3  page1_i93  (.a1(unnamed_1_capacitor_i77_b),
	.a2({glbl.gnd}),
	.a3({glbl.gnd}));
  defparam page1_i93.size = 1;

  \led-smd  page1_i94  (.a1(glbl.vcc),
	.k1(\unnamed_1_led-smd_i94_k1 ));
  defparam page1_i94.size = 1;

  \led-smd  page1_i95  (.a1(glbl.\2v5 ),
	.k1(\unnamed_1_led-smd_i95_k1 ));
  defparam page1_i95.size = 1;

  resistor page1_i96  (.a({glbl.gnd}),
	.b(\unnamed_1_led-smd_i95_k1 ));
  defparam page1_i96.size = 1;

  resistor page1_i97  (.a({glbl.gnd}),
	.b(\unnamed_1_led-smd_i94_k1 ));
  defparam page1_i97.size = 1;

  \pl-amp-050-68  page2_i2  (.a1(unnamed_2_100elt23_i10_d0),
	.a2(/* unconnected */),
	.a3(unnamed_2_100elt23_i10_d1),
	.a4(unnamed_2_100elt23_i11_d0),
	.a5(/* unconnected */),
	.a6(unnamed_2_100elt23_i11_d1),
	.a7(unnamed_2_100elt23_i12_d0),
	.a8(/* unconnected */),
	.a9(unnamed_2_100elt23_i12_d1),
	.a10(/* unconnected */),
	.a11(/* unconnected */),
	.a12(/* unconnected */),
	.a13(/* unconnected */),
	.a14(/* unconnected */),
	.a15(/* unconnected */),
	.a16(/* unconnected */),
	.a17(/* unconnected */),
	.a18(/* unconnected */),
	.a19(/* unconnected */),
	.a20(/* unconnected */),
	.a21(/* unconnected */),
	.a22(/* unconnected */),
	.a23(/* unconnected */),
	.a24(/* unconnected */),
	.a25(/* unconnected */),
	.a26(/* unconnected */),
	.a27(/* unconnected */),
	.a28(/* unconnected */),
	.a29(/* unconnected */),
	.a30(/* unconnected */),
	.a31(/* unconnected */),
	.a32(/* unconnected */),
	.a33(/* unconnected */),
	.a34(/* unconnected */),
	.a35(unnamed_2_100elt23_i10_d0_1),
	.a36(/* unconnected */),
	.a37(unnamed_2_100elt23_i10_d1_1),
	.a38(unnamed_2_100elt23_i11_d0_1),
	.a39(/* unconnected */),
	.a40(unnamed_2_100elt23_i11_d1_1),
	.a41(unnamed_2_100elt23_i12_d0_1),
	.a42(/* unconnected */),
	.a43(unnamed_2_100elt23_i12_d1_1),
	.a44(/* unconnected */),
	.a45(/* unconnected */),
	.a46(/* unconnected */),
	.a47(/* unconnected */),
	.a48(/* unconnected */),
	.a49(/* unconnected */),
	.a50(/* unconnected */),
	.a51(/* unconnected */),
	.a52(/* unconnected */),
	.a53(/* unconnected */),
	.a54(/* unconnected */),
	.a55(/* unconnected */),
	.a56(/* unconnected */),
	.a57(/* unconnected */),
	.a58(/* unconnected */),
	.a59(/* unconnected */),
	.a60(/* unconnected */),
	.a61(/* unconnected */),
	.a62(/* unconnected */),
	.a63(/* unconnected */),
	.a64(/* unconnected */),
	.a65(/* unconnected */),
	.a66(/* unconnected */),
	.a67(/* unconnected */),
	.a68(/* unconnected */));
  defparam page2_i2.size = 1;

  \sk-amp-050-68  page2_i3  (.a1(\unnamed_2_100324-dip_i25_op ),
	.a2(/* unconnected */),
	.a3(\unnamed_2_100324-dip_i30_op ),
	.a4(\unnamed_2_100324-dip_i29_op_1 ),
	.a5(/* unconnected */),
	.a6(\unnamed_2_100324-dip_i28_op ),
	.a7(\unnamed_2_100324-dip_i27_op ),
	.a8(/* unconnected */),
	.a9(\unnamed_2_100324-dip_i26_op ),
	.a10(/* unconnected */),
	.a11(/* unconnected */),
	.a12(/* unconnected */),
	.a13(/* unconnected */),
	.a14(/* unconnected */),
	.a15(/* unconnected */),
	.a16(/* unconnected */),
	.a17(/* unconnected */),
	.a18(/* unconnected */),
	.a19(/* unconnected */),
	.a20(/* unconnected */),
	.a21(/* unconnected */),
	.a22(/* unconnected */),
	.a23(/* unconnected */),
	.a24(/* unconnected */),
	.a25(/* unconnected */),
	.a26(/* unconnected */),
	.a27(/* unconnected */),
	.a28(/* unconnected */),
	.a29(/* unconnected */),
	.a30(/* unconnected */),
	.a31(/* unconnected */),
	.a32(/* unconnected */),
	.a33(/* unconnected */),
	.a34(/* unconnected */),
	.a35(\unnamed_2_100324-dip_i25_op_1 ),
	.a36(/* unconnected */),
	.a37(\unnamed_2_100324-dip_i30_op_1 ),
	.a38(\unnamed_2_100324-dip_i29_op ),
	.a39(/* unconnected */),
	.a40(\unnamed_2_100324-dip_i28_op_1 ),
	.a41(\unnamed_2_100324-dip_i27_op_1 ),
	.a42(/* unconnected */),
	.a43(\unnamed_2_100324-dip_i26_op_1 ),
	.a44(/* unconnected */),
	.a45(/* unconnected */),
	.a46(/* unconnected */),
	.a47(/* unconnected */),
	.a48(/* unconnected */),
	.a49(/* unconnected */),
	.a50(/* unconnected */),
	.a51(/* unconnected */),
	.a52(/* unconnected */),
	.a53(/* unconnected */),
	.a54(/* unconnected */),
	.a55(/* unconnected */),
	.a56(/* unconnected */),
	.a57(/* unconnected */),
	.a58(/* unconnected */),
	.a59(/* unconnected */),
	.a60(/* unconnected */),
	.a61(/* unconnected */),
	.a62(/* unconnected */),
	.a63(/* unconnected */),
	.a64(/* unconnected */),
	.a65(/* unconnected */),
	.a66(/* unconnected */),
	.a67(/* unconnected */),
	.a68(/* unconnected */));
  defparam page2_i3.size = 1;

  \100elt23  page2_i10  (.d0(unnamed_2_100elt23_i10_d0),
	.\d0* (unnamed_2_100elt23_i10_d0_1),
	.d1(unnamed_2_100elt23_i10_d1),
	.\d1* (unnamed_2_100elt23_i10_d1_1),
	.gnd(glbl.gnd),
	.q0(\unnamed_2_100324-dip_i25_d ),
	.q1(\unnamed_2_100324-dip_i30_d ),
	.vcc(glbl.vcc));
  defparam page2_i10.size = 1;

  \100elt23  page2_i11  (.d0(unnamed_2_100elt23_i11_d0),
	.\d0* (unnamed_2_100elt23_i11_d0_1),
	.d1(unnamed_2_100elt23_i11_d1),
	.\d1* (unnamed_2_100elt23_i11_d1_1),
	.gnd(glbl.gnd),
	.q0(\unnamed_2_100324-dip_i29_d ),
	.q1(\unnamed_2_100324-dip_i28_d ),
	.vcc(glbl.vcc));
  defparam page2_i11.size = 1;

  \100elt23  page2_i12  (.d0(unnamed_2_100elt23_i12_d0),
	.\d0* (unnamed_2_100elt23_i12_d0_1),
	.d1(unnamed_2_100elt23_i12_d1),
	.\d1* (unnamed_2_100elt23_i12_d1_1),
	.gnd(glbl.gnd),
	.q0(\unnamed_2_100324-dip_i27_d ),
	.q1(\unnamed_2_100324-dip_i26_d ),
	.vcc(glbl.vcc));
  defparam page2_i12.size = 1;

  \ten-5-dualop  page2_i13  (.vin_n1(\unnamed_2_ten-5-dualop_i13_vinn1 ),
	.vin_n2(\unnamed_2_ten-5-dualop_i13_vinn1 ),
	.vin_p1(\unnamed_2_ten-5-dualop_i13_vinp1 ),
	.vin_p2(\unnamed_2_ten-5-dualop_i13_vinp1 ),
	.vout_gnd1(glbl.gnd),
	.vout_gnd2(glbl.gnd),
	.vout_n1(glbl.vee),
	.vout_p1(glbl.vcc));

  \term-blk-3  page2_i14  (.a1(\unnamed_2_fuse-smd_i54_a ),
	.a2(\unnamed_2_ten-5-dualop_i13_vinn1 ),
	.a3(\unnamed_2_ten-5-dualop_i13_vinn1 ));
  defparam page2_i14.size = 1;

  capacitor page2_i18  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page2_i18.size = 1;

  capacitor page2_i19  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page2_i19.size = 1;

  capacitor page2_i20  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page2_i20.size = 1;

  capacitor page2_i21  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page2_i21.size = 1;

  capacitor page2_i22  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page2_i22.size = 1;

  \100324-dip  page2_i25  (.d(\unnamed_2_100324-dip_i25_d ),
	.en(\unnamed_2_100324-dip_i25_en ),
	.op(\unnamed_2_100324-dip_i25_op ),
	.\op* (\unnamed_2_100324-dip_i25_op_1 ));
  defparam page2_i25.size = 1;

  \100324-dip  page2_i26  (.d(\unnamed_2_100324-dip_i26_d ),
	.en(\unnamed_2_100324-dip_i25_en ),
	.op(\unnamed_2_100324-dip_i26_op ),
	.\op* (\unnamed_2_100324-dip_i26_op_1 ));
  defparam page2_i26.size = 1;

  \100324-dip  page2_i27  (.d(\unnamed_2_100324-dip_i27_d ),
	.en(\unnamed_2_100324-dip_i25_en ),
	.op(\unnamed_2_100324-dip_i27_op ),
	.\op* (\unnamed_2_100324-dip_i27_op_1 ));
  defparam page2_i27.size = 1;

  \100324-dip  page2_i28  (.d(\unnamed_2_100324-dip_i28_d ),
	.en(\unnamed_2_100324-dip_i25_en ),
	.op(\unnamed_2_100324-dip_i28_op ),
	.\op* (\unnamed_2_100324-dip_i28_op_1 ));
  defparam page2_i28.size = 1;

  \100324-dip  page2_i29  (.d(\unnamed_2_100324-dip_i29_d ),
	.en(\unnamed_2_100324-dip_i25_en ),
	.op(\unnamed_2_100324-dip_i29_op_1 ),
	.\op* (\unnamed_2_100324-dip_i29_op ));
  defparam page2_i29.size = 1;

  \100324-dip  page2_i30  (.d(\unnamed_2_100324-dip_i30_d ),
	.en(\unnamed_2_100324-dip_i25_en ),
	.op(\unnamed_2_100324-dip_i30_op ),
	.\op* (\unnamed_2_100324-dip_i30_op_1 ));
  defparam page2_i30.size = 1;

  capacitor page2_i44  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page2_i44.size = 1;

  capacitor page2_i46  (.a({glbl.gnd}),
	.b({glbl.vcc}));
  defparam page2_i46.size = 1;

  capacitor page2_i48  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page2_i48.size = 1;

  capacitor page2_i49  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page2_i49.size = 1;

  capacitor page2_i50  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page2_i50.size = 1;

  diode page2_i53  (.a(\unnamed_2_ten-5-dualop_i13_vinn1 ),
	.k(\unnamed_2_ten-5-dualop_i13_vinp1 ));
  defparam page2_i53.size = 1;

  \fuse-smd  page2_i54  (.a(\unnamed_2_fuse-smd_i54_a ),
	.b(\unnamed_2_ten-5-dualop_i13_vinp1 ));
  defparam page2_i54.size = 1;

  resistor page2_i64  (.a(\unnamed_2_100324-dip_i25_en ),
	.b({glbl.vcc}));
  defparam page2_i64.size = 1;

  resistor page2_i73  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i25_op_1 ));
  defparam page2_i73.size = 1;

  resistor page2_i78  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i26_op ));
  defparam page2_i78.size = 1;

  resistor page2_i79  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i26_op_1 ));
  defparam page2_i79.size = 1;

  resistor page2_i80  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i27_op ));
  defparam page2_i80.size = 1;

  resistor page2_i81  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i27_op_1 ));
  defparam page2_i81.size = 1;

  resistor page2_i82  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i28_op ));
  defparam page2_i82.size = 1;

  resistor page2_i83  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i28_op_1 ));
  defparam page2_i83.size = 1;

  resistor page2_i84  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i29_op_1 ));
  defparam page2_i84.size = 1;

  resistor page2_i85  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i29_op ));
  defparam page2_i85.size = 1;

  resistor page2_i86  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i30_op ));
  defparam page2_i86.size = 1;

  resistor page2_i87  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i30_op_1 ));
  defparam page2_i87.size = 1;

  resistor page2_i88  (.a({glbl.vee}),
	.b(\unnamed_2_100324-dip_i25_op ));
  defparam page2_i88.size = 1;

  resistor page2_i89  (.a(unnamed_2_100elt23_i10_d0),
	.b(unnamed_2_100elt23_i10_d0_1));
  defparam page2_i89.size = 1;

  resistor page2_i90  (.a(unnamed_2_100elt23_i10_d1),
	.b(unnamed_2_100elt23_i10_d1_1));
  defparam page2_i90.size = 1;

  resistor page2_i91  (.a(unnamed_2_100elt23_i11_d0),
	.b(unnamed_2_100elt23_i11_d0_1));
  defparam page2_i91.size = 1;

  resistor page2_i92  (.a(unnamed_2_100elt23_i11_d1),
	.b(unnamed_2_100elt23_i11_d1_1));
  defparam page2_i92.size = 1;

  resistor page2_i93  (.a(unnamed_2_100elt23_i12_d0),
	.b(unnamed_2_100elt23_i12_d0_1));
  defparam page2_i93.size = 1;

  resistor page2_i94  (.a(unnamed_2_100elt23_i12_d1),
	.b(unnamed_2_100elt23_i12_d1_1));
  defparam page2_i94.size = 1;

  \term-blk-3  page3_i14  (.a1(\unnamed_3_fuse-smd_i54_a ),
	.a2(unnamed_3_diode_i53_a),
	.a3(unnamed_3_diode_i53_a));
  defparam page3_i14.size = 1;

  capacitor page3_i19  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page3_i19.size = 1;

  capacitor page3_i48  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page3_i48.size = 1;

  capacitor page3_i49  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page3_i49.size = 1;

  capacitor page3_i50  (.a({glbl.vee}),
	.b({glbl.gnd}));
  defparam page3_i50.size = 1;

  diode page3_i53  (.a(unnamed_3_diode_i53_a),
	.k(unnamed_3_diode_i53_k));
  defparam page3_i53.size = 1;

  \fuse-smd  page3_i54  (.a(\unnamed_3_fuse-smd_i54_a ),
	.b(unnamed_3_diode_i53_k));
  defparam page3_i54.size = 1;

  \ten-5  page3_i55  (.vin_n1(unnamed_3_diode_i53_a),
	.vin_n2(unnamed_3_diode_i53_a),
	.vin_p1(unnamed_3_diode_i53_k),
	.vin_p2(unnamed_3_diode_i53_k),
	.vout_n1(glbl.vee),
	.vout_p1(glbl.gnd));

  \sk-amp-050-68  page3_i73  (.a1(unnamed_3_resistor_i99_b),
	.a2(unnamed_3_resistor_i113_b),
	.a3(unnamed_3_resistor_i111_b),
	.a4(unnamed_3_resistor_i109_b),
	.a5(unnamed_3_resistor_i107_b),
	.a6(unnamed_3_resistor_i105_b),
	.a7(unnamed_3_resistor_i103_b),
	.a8(unnamed_3_resistor_i101_b),
	.a9(/* unconnected */),
	.a10(/* unconnected */),
	.a11(/* unconnected */),
	.a12(/* unconnected */),
	.a13(/* unconnected */),
	.a14(/* unconnected */),
	.a15(/* unconnected */),
	.a16(/* unconnected */),
	.a17(/* unconnected */),
	.a18(/* unconnected */),
	.a19(/* unconnected */),
	.a20(/* unconnected */),
	.a21(/* unconnected */),
	.a22(/* unconnected */),
	.a23(/* unconnected */),
	.a24(/* unconnected */),
	.a25(/* unconnected */),
	.a26(/* unconnected */),
	.a27(/* unconnected */),
	.a28(/* unconnected */),
	.a29(/* unconnected */),
	.a30(/* unconnected */),
	.a31(unnamed_3_resistor_i76_a),
	.a32(/* unconnected */),
	.a33(unnamed_3_resistor_i78_a),
	.a34(/* unconnected */),
	.a35(unnamed_3_resistor_i114_b),
	.a36(unnamed_3_resistor_i112_b),
	.a37(unnamed_3_resistor_i110_b),
	.a38(unnamed_3_resistor_i108_b),
	.a39(unnamed_3_resistor_i106_b),
	.a40(unnamed_3_resistor_i104_b),
	.a41(unnamed_3_resistor_i102_b),
	.a42(unnamed_3_resistor_i100_b),
	.a43(/* unconnected */),
	.a44(/* unconnected */),
	.a45(/* unconnected */),
	.a46(/* unconnected */),
	.a47(/* unconnected */),
	.a48(/* unconnected */),
	.a49(/* unconnected */),
	.a50(/* unconnected */),
	.a51(/* unconnected */),
	.a52(/* unconnected */),
	.a53(/* unconnected */),
	.a54(/* unconnected */),
	.a55(/* unconnected */),
	.a56(/* unconnected */),
	.a57(/* unconnected */),
	.a58(/* unconnected */),
	.a59(/* unconnected */),
	.a60(/* unconnected */),
	.a61(/* unconnected */),
	.a62(/* unconnected */),
	.a63(/* unconnected */),
	.a64(/* unconnected */),
	.a65(unnamed_3_resistor_i77_a),
	.a66(/* unconnected */),
	.a67(unnamed_3_resistor_i78_a),
	.a68(/* unconnected */));
  defparam page3_i73.size = 1;

  \sk-amp-050-68  page3_i74  (.a1(unnamed_3_resistor_i99_b),
	.a2(unnamed_3_resistor_i113_b),
	.a3(unnamed_3_resistor_i111_b),
	.a4(unnamed_3_resistor_i109_b),
	.a5(unnamed_3_resistor_i107_b),
	.a6(unnamed_3_resistor_i105_b),
	.a7(unnamed_3_resistor_i103_b),
	.a8(unnamed_3_resistor_i101_b),
	.a9(/* unconnected */),
	.a10(/* unconnected */),
	.a11(/* unconnected */),
	.a12(/* unconnected */),
	.a13(/* unconnected */),
	.a14(/* unconnected */),
	.a15(/* unconnected */),
	.a16(/* unconnected */),
	.a17(/* unconnected */),
	.a18(/* unconnected */),
	.a19(/* unconnected */),
	.a20(/* unconnected */),
	.a21(/* unconnected */),
	.a22(/* unconnected */),
	.a23(/* unconnected */),
	.a24(/* unconnected */),
	.a25(/* unconnected */),
	.a26(/* unconnected */),
	.a27(/* unconnected */),
	.a28(/* unconnected */),
	.a29(/* unconnected */),
	.a30(/* unconnected */),
	.a31(unnamed_3_resistor_i81_a),
	.a32(/* unconnected */),
	.a33(unnamed_3_resistor_i83_b),
	.a34(/* unconnected */),
	.a35(unnamed_3_resistor_i114_b),
	.a36(unnamed_3_resistor_i112_b),
	.a37(unnamed_3_resistor_i110_b),
	.a38(unnamed_3_resistor_i108_b),
	.a39(unnamed_3_resistor_i106_b),
	.a40(unnamed_3_resistor_i104_b),
	.a41(unnamed_3_resistor_i102_b),
	.a42(unnamed_3_resistor_i100_b),
	.a43(/* unconnected */),
	.a44(/* unconnected */),
	.a45(/* unconnected */),
	.a46(/* unconnected */),
	.a47(/* unconnected */),
	.a48(/* unconnected */),
	.a49(/* unconnected */),
	.a50(/* unconnected */),
	.a51(/* unconnected */),
	.a52(/* unconnected */),
	.a53(/* unconnected */),
	.a54(/* unconnected */),
	.a55(/* unconnected */),
	.a56(/* unconnected */),
	.a57(/* unconnected */),
	.a58(/* unconnected */),
	.a59(/* unconnected */),
	.a60(/* unconnected */),
	.a61(/* unconnected */),
	.a62(/* unconnected */),
	.a63(/* unconnected */),
	.a64(/* unconnected */),
	.a65(unnamed_3_resistor_i82_a),
	.a66(/* unconnected */),
	.a67(unnamed_3_resistor_i83_b),
	.a68(/* unconnected */));
  defparam page3_i74.size = 1;

  resistor page3_i76  (.a(unnamed_3_resistor_i76_a),
	.b({glbl.gnd}));
  defparam page3_i76.size = 1;

  resistor page3_i77  (.a(unnamed_3_resistor_i77_a),
	.b({glbl.gnd}));
  defparam page3_i77.size = 1;

  resistor page3_i78  (.a(unnamed_3_resistor_i78_a),
	.b({glbl.gnd}));
  defparam page3_i78.size = 1;

  resistor page3_i81  (.a(unnamed_3_resistor_i81_a),
	.b(unnamed_3_resistor_i81_b));
  defparam page3_i81.size = 1;

  resistor page3_i82  (.a(unnamed_3_resistor_i82_a),
	.b(unnamed_3_resistor_i82_b));
  defparam page3_i82.size = 1;

  resistor page3_i83  (.a(unnamed_3_resistor_i83_a),
	.b(unnamed_3_resistor_i83_b));
  defparam page3_i83.size = 1;

  resistor page3_i84  (.a(unnamed_3_resistor_i77_a),
	.b(unnamed_3_resistor_i84_b));
  defparam page3_i84.size = 1;

  resistor page3_i85  (.a(unnamed_3_resistor_i76_a),
	.b(unnamed_3_resistor_i85_b));
  defparam page3_i85.size = 1;

  resistor page3_i86  (.a(unnamed_3_resistor_i86_a),
	.b(unnamed_3_resistor_i78_a));
  defparam page3_i86.size = 1;

  \sk-sma-pcb  page3_i87  (.a(unnamed_3_resistor_i86_a));
  defparam page3_i87.size = 1;

  \sk-sma-pcb  page3_i88  (.a(unnamed_3_resistor_i85_b));
  defparam page3_i88.size = 1;

  \sk-sma-pcb  page3_i89  (.a(unnamed_3_resistor_i84_b));
  defparam page3_i89.size = 1;

  \sk-sma-pcb  page3_i90  (.a(unnamed_3_resistor_i97_a));
  defparam page3_i90.size = 1;

  \sk-sma-pcb  page3_i91  (.a(unnamed_3_resistor_i98_a));
  defparam page3_i91.size = 1;

  \sk-sma-pcb  page3_i92  (.a(unnamed_3_resistor_i83_a));
  defparam page3_i92.size = 1;

  \sk-sma-pcb  page3_i93  (.a(unnamed_3_resistor_i81_b));
  defparam page3_i93.size = 1;

  \sk-sma-pcb  page3_i94  (.a(unnamed_3_resistor_i82_b));
  defparam page3_i94.size = 1;

  \sk-sma-pcb  page3_i95  (.a(unnamed_3_resistor_i96_a));
  defparam page3_i95.size = 1;

  resistor page3_i96  (.a(unnamed_3_resistor_i96_a),
	.b(unnamed_3_resistor_i83_b));
  defparam page3_i96.size = 1;

  resistor page3_i97  (.a(unnamed_3_resistor_i97_a),
	.b(unnamed_3_resistor_i82_a));
  defparam page3_i97.size = 1;

  resistor page3_i98  (.a(unnamed_3_resistor_i98_a),
	.b(unnamed_3_resistor_i81_a));
  defparam page3_i98.size = 1;

  resistor page3_i99  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i99_b));
  defparam page3_i99.size = 1;

  resistor page3_i100  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i100_b));
  defparam page3_i100.size = 1;

  resistor page3_i101  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i101_b));
  defparam page3_i101.size = 1;

  resistor page3_i102  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i102_b));
  defparam page3_i102.size = 1;

  resistor page3_i103  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i103_b));
  defparam page3_i103.size = 1;

  resistor page3_i104  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i104_b));
  defparam page3_i104.size = 1;

  resistor page3_i105  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i105_b));
  defparam page3_i105.size = 1;

  resistor page3_i106  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i106_b));
  defparam page3_i106.size = 1;

  resistor page3_i107  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i107_b));
  defparam page3_i107.size = 1;

  resistor page3_i108  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i108_b));
  defparam page3_i108.size = 1;

  resistor page3_i109  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i109_b));
  defparam page3_i109.size = 1;

  resistor page3_i110  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i110_b));
  defparam page3_i110.size = 1;

  resistor page3_i111  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i111_b));
  defparam page3_i111.size = 1;

  resistor page3_i112  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i112_b));
  defparam page3_i112.size = 1;

  resistor page3_i113  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i113_b));
  defparam page3_i113.size = 1;

  resistor page3_i114  (.a({glbl.vee}),
	.b(unnamed_3_resistor_i114_b));
  defparam page3_i114.size = 1;

endmodule // qpll(sch_1) 
